### ISSUE TITLE
PFWMA-272 - Add rule based on buyer language using WPML.

### ISSUE THREAD

**Issue by drewangell** [angelleye/paypal-for-woocommerce-multi-account-management#106]
# Story

As a merchant using PFWMA and WPML, I need the ability to create payment rules based on the buyer’s language.

# Details

The plugin currently supports WPML in general for translation (or at least it should), but it does not currently have a rule specifically for paying accounts based on the WPML language of the buyer.

WPML allows buyers to choose their language, and the rule should be triggered based on this.

The site owner will be able to create the rule by specifying which WML language(s) should trigger which PayPal account(s).

**Comment by devchristina2** [comment]
Hi,

Thank you for reaching out and submitting an issue on our GitHub repository.

We wanted to inform you that we’ve temporarily paused active support for this repository and will close all open issues, including this one. If you require further assistance or have additional questions, please submit a support ticket through our [Help Center](https://angelleye.atlassian.net/servicedesk/customer/portals), where our support team will be happy to assist you.

We appreciate your understanding and apologize for any inconvenience. Thank you for being part of our community!

Thanks, Christina.
