### ISSUE TITLE
OFW-172 - Woo Product Vendors Compatibility

### ISSUE THREAD

**Issue by drewangell** [angelleye/paypal-for-woocommerce-multi-account-management#107]
# Story

As a site admin, I need OFW to work with Woo Product Vendors, so that my vendors can manage their own offers directly.

# Details

*   We did for [WC Vendors](https://www.angelleye.com/product/offers-for-woocommerce-wc-vendors/ "https://www.angelleye.com/product/offers-for-woocommerce-wc-vendors/") and [Dokan](https://www.angelleye.com/product/offers-for-woocommerce-dokan/ "https://www.angelleye.com/product/offers-for-woocommerce-dokan/"). Just need to do the same thing for Woo Product Vendors.

**Comment by devchristina2** [comment]
Hi,

Thank you for reaching out and submitting an issue on our GitHub repository.

We wanted to inform you that we’ve temporarily paused active support for this repository and will close all open issues, including this one. If you require further assistance or have additional questions, please submit a support ticket through our [Help Center](https://angelleye.atlassian.net/servicedesk/customer/portals), where our support team will be happy to assist you.

We appreciate your understanding and apologize for any inconvenience. Thank you for being part of our community!

Thanks, Christina.
