### ISSUE TITLE
PFWMA-173 - Woo Deposits Compatibility

### ISSUE THREAD

**Issue by drewangell** [angelleye/paypal-for-woocommerce-multi-account-management#108]
# Story

As the site admin, I need PFWMA to work well with the Woo Deposits plugin, so that the installment payments can be paid to the secondary account(s) as necessary.

# Details

While [PayPal Pay Later](https://www.angelleye.com/paypal-buy-now-pay-later-interest-free-financing/ "https://www.angelleye.com/paypal-buy-now-pay-later-interest-free-financing/") does provide installment plans, this plugin would be a bit more flexible. We need to research exactly how this plugin is handling the installment payments (most likely reference transactions / token payments) and implement this into our PFWMA integration.

# Acceptance Criteria

*   Buyers can checkout using the installment option(s) provided by the Woo Deposits plugin.
    
*   PFWMA rules are triggered for installment payments, so that the product owner (vendor) gets paid directly.

**Comment by devchristina2** [comment]
Hi,

Thank you for reaching out and submitting an issue on our GitHub repository.

We wanted to inform you that we’ve temporarily paused active support for this repository and will close all open issues, including this one. If you require further assistance or have additional questions, please submit a support ticket through our [Help Center](https://angelleye.atlassian.net/servicedesk/customer/portals), where our support team will be happy to assist you.

We appreciate your understanding and apologize for any inconvenience. Thank you for being part of our community!

Thanks, Christina.
