### ISSUE TITLE
Add Option to Pay All Tax to Marketplace Account

### ISSUE THREAD

**Issue by drewangell** [angelleye/paypal-for-woocommerce-multi-account-management#88]
# Story

As the site/marketplace owner, I need all of the taxes on orders paid to my account, so that I can submit those taxes to my state based as required.

# Details

Currently, taxes are being calculated and included in the amount that goes to the product owner / vendor.  

Some marketplaces do not want this, and instead need to collect the taxes themselves.  This won’t be the case for everybody, though.

## Solution

We need to add an option in the PFWMA settings for the site owner to choose which way they want to handle this.

**Tax Handling**

* Sales tax should be paid to the marketplace (primary) PayPal account.
* Sales tax should be paid directly to product owners / vendors.

**Comment by devchristina2** [comment]
Hi,

Thank you for reaching out and submitting an issue on our GitHub repository.

We wanted to inform you that we’ve temporarily paused active support for this repository and will close all open issues, including this one. If you require further assistance or have additional questions, please submit a support ticket through our [Help Center](https://angelleye.atlassian.net/servicedesk/customer/portals), where our support team will be happy to assist you.

We appreciate your understanding and apologize for any inconvenience. Thank you for being part of our community!

Thanks, Christina.
