### ISSUE TITLE
Send Shipping Amount to a Specified Account

### ISSUE THREAD

**Issue by drewangell** [angelleye/paypal-for-woocommerce-multi-account-management#91]
# Story

As a site admin, I need the ability to create a rule for shipping cost, so that the shipping amount on the order can be be separated and sent to the PayPal account specified.

# Example

* Order has 3 products at $20/each, that are from 3 separate vendors.
* Order also has shipping amount of $15.00.
* Each vendor should receive their $20 payment directly, and the shipping of $15 should be sent to the account set for shipping.

# Considerations

* Shipping Class rules would need to be overridden if this feature is enabled.
* Any shipping splits that would normally happen would also be overridden when this feature is enabled.

# Acceptance Criteria

* I can create a rule in PFWMA to have the shipping amount paid to a specified PayPal account.
* Upon checkout, the shipping amount is paid to this specified account, while the item details and tax are paid to the secondary accounts as usual.

**Comment by devchristina2** [comment]
Hi,

Thank you for reaching out and submitting an issue on our GitHub repository.

We wanted to inform you that we’ve temporarily paused active support for this repository and will close all open issues, including this one. If you require further assistance or have additional questions, please submit a support ticket through our [Help Center](https://angelleye.atlassian.net/servicedesk/customer/portals), where our support team will be happy to assist you.

We appreciate your understanding and apologize for any inconvenience. Thank you for being part of our community!

Thanks, Christina.
