### ISSUE TITLE
WCFM Automated Rule Creation

### ISSUE THREAD

**Issue by drewangell** [angelleye/paypal-for-woocommerce-multi-account-management#92]
# Story

As a site admin, I need Multi-Account rules to be created automatically for vendors when they register, so that I do not have to do this manually.

# Acceptance Criteria

* In PFWMA Settings, I see a WCFM Settings section in the admin panel where I can enable/disable automatic rule creation.
* This also includes the option to enable/disable sandbox for these automated rules.
* From the PFWMA Accounts screen, I can “Sync Existing Vendor Rules” and “Disable All Auto-Generated Vendor Rules”.
* When a new WCFM vendor registers for the site, a rule is automatically created for them in PFWMA Accounts.
* If an existing vendor updates their PayPal email address in WCFM, the rule is automatically updated to match this new email.

**Comment by devchristina2** [comment]
Hi,

Thank you for reaching out and submitting an issue on our GitHub repository.

We wanted to inform you that we’ve temporarily paused active support for this repository and will close all open issues, including this one. If you require further assistance or have additional questions, please submit a support ticket through our [Help Center](https://angelleye.atlassian.net/servicedesk/customer/portals), where our support team will be happy to assist you.

We appreciate your understanding and apologize for any inconvenience. Thank you for being part of our community!

Thanks, Christina.
