### ISSUE TITLE
Add a rule to define a payment limit for each account in the Load Balancer.

### ISSUE THREAD

**Issue by drewangell** [angelleye/paypal-for-woocommerce-multi-account-management#96]
# Story

As a site admin using the Load Balancer, I would like a way to specify a revenue limit for each account, so that I can use each account up to that limit before switching to the next account on the list.

Each account could have separate limits.  For example:

Account A - Limit $5,000 - Orders are paid here until $5k in volume is reached.  Then move to Account B.
Account B - Limit $10,000 - Orders are paid here until $10 in volume is reached.  Then move to Account C.
and so on...

# Additional Info

* If an order would put an account over its limit, move to the next account so that we never go over a limit.
* We will not need to consider a “daily” clock here.  We can simply do this based on the total amounts processed.

**Comment by devchristina2** [comment]
Hi,

Thank you for reaching out and submitting an issue on our GitHub repository.

We wanted to inform you that we’ve temporarily paused active support for this repository and will close all open issues, including this one. If you require further assistance or have additional questions, please submit a support ticket through our [Help Center](https://angelleye.atlassian.net/servicedesk/customer/portals), where our support team will be happy to assist you.

We appreciate your understanding and apologize for any inconvenience. Thank you for being part of our community!

Thanks, Christina.
